spring:
  application:
    name: TaskManager_REASTFull

  datasource:
    url: jdbc:mysql://localhost:3306/tasks_bd
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    web:
      pageable:
        max-page-size: 100
